import { Inter } from "next/font/google";
import "./globals.css";
import StarsCanvas from "./components/Background";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StarsCanvas />
        {children}
      </body>
    </html>
  );
}
